### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by Artexoid** [PHPixie/Route#3]
Здравствуйте.

Подскажите, где я могу посмотреть примеры как это использовать?? Никакую документацию по библиотеке не смог найти.

**Comment by dracony** [comment]
Poka toljko quickstart,  nu i v chate mozhem pomochj. Doku nado dopisatj.
spasibo chto napomnil.

2017-02-28 15:21 GMT-08:00 Artem <notifications@github.com>:

**Comment by dracony** [comment]
slovom zahodi v chat :)
